# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Abachouch Youssouf
email: youssouf.abachouch@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I’m Abachouch Youssouf, a Full-Stack Developer with a passion for creating robust, end-to-end web applications. From crafting intuitive frontends to architecting powerful backends, I build digital solutions that drive success.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abachouch.online" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: y0u553f
github_username: A.Youssouf
linkedin_username: efdfwef
facebook_username: qjf8o
instagram_username: jiwjefj
dribbble_username: jiejee
rss: true
google_analytics: G-2RJ308YXWK

include:
  - _pages

collections:
  works:
    output: true
    permalink: /work/:title/
  tips:
    output: true
    permalink: /tips/:title/
  projects:
    output: true
    permalink: /projects/:title/

nav_links:
  - name: Home
    link: /
  - name: Side Projects
    link: /side-projects/
  - name: Work Case Studies
    link: /work/
  - name: About
    link: /about/
  - name: Tips and Tricks
    link: /tips/
  - name: Contact Me
    link: /contact/

# Build settings
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

